### ISSUE TITLE
com.itextpdf.kernel.PdfException: No glyphs defined for type3 font

### ISSUE THREAD

**Issue by cha5on** [BitCurator/bitcurator-redact-pdf#1]
Hello,

When I try to redact some content within a PDF, clicking the "Redact" does not result in any visible operation.  Looking at the console shows an exception about "No glyphs defined for type3 font".  I realize that this is caused by itextpdf, but the bug here is that the message isn't passed along to the end user in an easily visible way.

More from the log:

```
2019-06-15 16:44:43 INFO  Ghostscript:72 - GPL Ghostscript 9.26 (2018-11-20)
2019-06-15 16:44:43 INFO  Ghostscript:72 - Copyright (C) 2018 Artifex Software, Inc.  All rights reserved.
2019-06-15 16:44:43 INFO  Ghostscript:72 - This software comes with NO WARRANTY: see the file PUBLIC for details.
2019-06-15 16:44:43 INFO  Ghostscript:72 - Processing pages 1 through 1.
2019-06-15 16:44:43 INFO  Ghostscript:72 - Page 1
2019-06-15 16:44:43 INFO  Ghostscript:72 - Loading NimbusRoman-Regular font from /usr/share/ghostscript/9.26/Resource/Font/NimbusRoman-Regular... 4553148 2989691 8950112 7575033 4 done.
2019-06-15 16:44:43 INFO  Ghostscript:72 - Loading NimbusSans-Regular font from /usr/share/ghostscript/9.26/Resource/Font/NimbusSans-Regular... 4659660 3292791 9394512 7996884 4 done.
2019-06-15 16:44:43 INFO  Ghostscript:72 - Loading NimbusSans-Bold font from /usr/share/ghostscript/9.26/Resource/Font/NimbusSans-Bold... 4846972 3487020 9394512 8008372 4 done.
2019-06-15 16:44:43 INFO  RedactDialog:372 - size of image list: 1
2019-06-15 16:45:30 INFO  RedactDialog:290 - in redact button handler
2019-06-15 16:45:30 INFO  RedactDialog:296 - in redact button handler, past the asks check
2019-06-15 16:45:30 INFO  RedactDialog:301 - in redact button handler, starting cleanup
2019-06-15 16:45:31 INFO  RedactDialog:303 - in redact button handler, past the cleanup operation
Exception in thread "AWT-EventQueue-0" com.itextpdf.kernel.PdfException: No glyphs defined for type3 font.
	at com.itextpdf.kernel.font.PdfType3Font.flush(PdfType3Font.java:309)
	at com.itextpdf.kernel.pdf.PdfDocument.flushFonts(PdfDocument.java:1949)
	at com.itextpdf.kernel.pdf.PdfDocument.close(PdfDocument.java:854)
	at bca.redact.RedactDialog.closeDoc(RedactDialog.java:311)
	at bca.redact.RedactDialog.redactButtonHandler(RedactDialog.java:307)
	at bca.redact.RedactDialog$3.actionPerformed(RedactDialog.java:182)
	at java.desktop/java.awt.Button.processActionEvent(Button.java:411)
	at java.desktop/java.awt.Button.processEvent(Button.java:379)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.itextpdf.kernel.pdf.PdfDictionary.get(PdfDictionary.java:456)
	at com.itextpdf.kernel.pdf.PdfDictionary.getAsArray(PdfDictionary.java:156)
	at com.itextpdf.kernel.pdf.PdfPage.getMediaBox(PdfPage.java:516)
	at com.itextpdf.kernel.pdf.PdfPage.getPageSize(PdfPage.java:125)
	at bca.redact.PreviewPanel.setPDFLocation(PreviewPanel.java:71)
	at bca.redact.RedactDialog.markPageLocation(RedactDialog.java:286)
	at bca.redact.RedactDialog$5.mousePressed(RedactDialog.java:230)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

I can't include the PDF that caused this, unfortunately, since there's a reason I'm trying to redact it in the first place.

**Comment by kamwoods** [comment]
Development on this research tool ended in 2018. It is effectively defunct as it no longer has an active maintainer.

**Comment by kamwoods** [comment]
Closing as this repository is now end-of-life.
